### ISSUE TITLE
another open ag initiative

### ISSUE THREAD

**Issue by thiemehennis** [CommonGarden/awesome-open-ag#1]
I'm here plugging our own initiative: AstroPlant - a collaboration with the European Space Agency.

Sorry for not Pull requesting, I'm not using Github very often. We do publish all on Github (check AstroPlant) and on WeVolver. Our website is astroplant.io

AstroPlant is a citizen science project and DIY plant lab to monitor plant growth and help plant scientists at the European Space Agency and related institutions in their quest to fully characterise a large number of plant species and cultivars. It is built by a number of volunteers and coordinated by Border Labs and the European Space Agency. The research partner in the project is the MELiSSA consortium, which is working on regenerative, closed loop life support systems for space. This system consists of 5 compartments to turn the metabolic waste of the plants, algae, and crew members into endless supplies of water, food, and oxygen. To do that, it is essential to have a very high level of understanding of, and control over plants and their growth. To create this understanding, relatively affordable open-source AstroPlant kits are distributed across the world, including seeds provided by ESA, where plants are cultivated and grown under varying environmental conditions. It’s the variety in these conditions that scientists need to create better mathematical models of plants and to ultimately be able to control their growth. 

AstroPlant is as much a science project as an educational project, and is developing intuitive user and learning experiences to effectively convey the various educational themes represented by the kit: space exploration, circular systems design, ecology and biology, plant science, (open source) hardware design, automation and electronics.

**Comment by JakeHartnell** [comment]
Added! Very cool project.
